In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.3 MB 3.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.3 MB 5.6 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 11.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
#create the numpy array
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
print(np.__version__)
print(type(a))
print(a.shape)
print(a.ndim)

2.4.2
<class 'numpy.ndarray'>
(5,)
1


In [10]:
b=np.array((1,2,3,4,5))
print(type(b))
print(b.shape)
print(b.ndim)

<class 'numpy.ndarray'>
(5,)
1


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [12]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3


In [17]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[::-1])
print(arr[-5:-1])

1
[5 4 3 2 1]
[1 2 3 4]


In [18]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [19]:
print(arr[:,1:,1:])

[[[ 5  6]]

 [[11 12]]]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
#Iterating arrays nditer() function is used to iterate an array element by element.

'''what difference between nditer and normal for loop is that nditer is more
 efficient than normal for loop and it is also faster than normal for loop'''
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [26]:
#Enumerated Iteration Using ndenumerate() 
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [37]:
arr=np.array([1,2,34,4,5,4])
x=np.where(arr==4)
print(x)

(array([3, 5]),)


In [ ]:
'''There is a method called searchsorted() which performs a binary search in the array, 
and returns the index where the specified value would be inserted to maintain the search order.'''
arr=np.array([1,2,3,9,2,4,6,8,9])
x=np.searchsorted(arr,5)
print(x)

6


In [42]:
arr=np.array([1,6,34,3,2,1])
print(np.sort(arr))

[ 1  1  2  3  6 34]
